[2023-04-16T13:37:00.383+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: joke_collector.joke_collector_task scheduled__2023-04-15T15:18:00+00:00 [queued]>
[2023-04-16T13:37:00.635+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: joke_collector.joke_collector_task scheduled__2023-04-15T15:18:00+00:00 [queued]>
[2023-04-16T13:37:00.639+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-16T13:37:00.643+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 2
[2023-04-16T13:37:00.658+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-16T13:37:01.291+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonVirtualenvOperator): joke_collector_task> on 2023-04-15 15:18:00+00:00
[2023-04-16T13:37:01.317+0000] {standard_task_runner.py:55} INFO - Started process 379 to run task
[2023-04-16T13:37:01.366+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'joke_collector', 'joke_collector_task', 'scheduled__2023-04-15T15:18:00+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/dag_joke_collector.py', '--cfg-path', '/tmp/tmp0i_lae7c']
[2023-04-16T13:37:01.369+0000] {standard_task_runner.py:83} INFO - Job 55: Subtask joke_collector_task
[2023-04-16T13:37:01.994+0000] {task_command.py:389} INFO - Running <TaskInstance: joke_collector.joke_collector_task scheduled__2023-04-15T15:18:00+00:00 [running]> on host 09657e5e4ab9
[2023-04-16T13:37:02.866+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=joke_collector
AIRFLOW_CTX_TASK_ID=joke_collector_task
AIRFLOW_CTX_EXECUTION_DATE=2023-04-15T15:18:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-15T15:18:00+00:00
[2023-04-16T13:37:02.901+0000] {process_utils.py:179} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venvwz3jbw_n --system-site-packages
[2023-04-16T13:37:02.950+0000] {process_utils.py:183} INFO - Output:
[2023-04-16T13:37:10.024+0000] {process_utils.py:187} INFO - created virtual environment CPython3.7.16.final.0-64 in 1667ms
[2023-04-16T13:37:10.027+0000] {process_utils.py:187} INFO -   creator CPython3Posix(dest=/tmp/venvwz3jbw_n, clear=False, no_vcs_ignore=False, global=True)
[2023-04-16T13:37:10.029+0000] {process_utils.py:187} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2023-04-16T13:37:10.035+0000] {process_utils.py:187} INFO -     added seed packages: pip==23.0.1, setuptools==67.6.1, wheel==0.40.0
[2023-04-16T13:37:10.038+0000] {process_utils.py:187} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2023-04-16T13:37:10.182+0000] {process_utils.py:179} INFO - Executing cmd: /tmp/venvwz3jbw_n/bin/pip install -r /tmp/venvwz3jbw_n/requirements.txt
[2023-04-16T13:37:10.229+0000] {process_utils.py:183} INFO - Output:
[2023-04-16T13:37:22.404+0000] {process_utils.py:187} INFO - Collecting requests==2.25.1
[2023-04-16T13:37:22.482+0000] {process_utils.py:187} INFO -   Using cached requests-2.25.1-py2.py3-none-any.whl (61 kB)
[2023-04-16T13:37:23.028+0000] {process_utils.py:187} INFO - Collecting idna<3,>=2.5
[2023-04-16T13:37:23.094+0000] {process_utils.py:187} INFO -   Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
[2023-04-16T13:37:23.119+0000] {process_utils.py:187} INFO - Requirement already satisfied: chardet<5,>=3.0.2 in /home/***/.local/lib/python3.7/site-packages (from requests==2.25.1->-r /tmp/venvwz3jbw_n/requirements.txt (line 1)) (4.0.0)
[2023-04-16T13:37:23.136+0000] {process_utils.py:187} INFO - Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/***/.local/lib/python3.7/site-packages (from requests==2.25.1->-r /tmp/venvwz3jbw_n/requirements.txt (line 1)) (1.26.15)
[2023-04-16T13:37:23.167+0000] {process_utils.py:187} INFO - Requirement already satisfied: certifi>=2017.4.17 in /home/***/.local/lib/python3.7/site-packages (from requests==2.25.1->-r /tmp/venvwz3jbw_n/requirements.txt (line 1)) (2022.12.7)
[2023-04-16T13:38:17.131+0000] {process_utils.py:187} INFO - Installing collected packages: idna, requests
[2023-04-16T13:38:17.134+0000] {process_utils.py:187} INFO -   Attempting uninstall: idna
[2023-04-16T13:38:17.143+0000] {process_utils.py:187} INFO -     Found existing installation: idna 3.4
[2023-04-16T13:38:17.165+0000] {process_utils.py:187} INFO -     Not uninstalling idna at /home/***/.local/lib/python3.7/site-packages, outside environment /tmp/venvwz3jbw_n
[2023-04-16T13:38:17.169+0000] {process_utils.py:187} INFO -     Can't uninstall 'idna'. No files were found to uninstall.
[2023-04-16T13:38:17.797+0000] {process_utils.py:187} INFO -   Attempting uninstall: requests
[2023-04-16T13:38:17.817+0000] {process_utils.py:187} INFO -     Found existing installation: requests 2.28.2
[2023-04-16T13:38:17.820+0000] {process_utils.py:187} INFO -     Not uninstalling requests at /home/***/.local/lib/python3.7/site-packages, outside environment /tmp/venvwz3jbw_n
[2023-04-16T13:38:17.821+0000] {process_utils.py:187} INFO -     Can't uninstall 'requests'. No files were found to uninstall.
[2023-04-16T13:38:18.206+0000] {process_utils.py:187} INFO - ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
[2023-04-16T13:38:18.207+0000] {process_utils.py:187} INFO - hvac 1.1.0 requires requests<3.0.0,>=2.27.1, but you have requests 2.25.1 which is incompatible.
[2023-04-16T13:38:18.209+0000] {process_utils.py:187} INFO - docker 6.0.1 requires requests>=2.26.0, but you have requests 2.25.1 which is incompatible.
[2023-04-16T13:38:18.210+0000] {process_utils.py:187} INFO - apache-***-providers-http 4.2.0 requires requests>=2.26.0, but you have requests 2.25.1 which is incompatible.
[2023-04-16T13:38:18.211+0000] {process_utils.py:187} INFO - Successfully installed idna-2.10 requests-2.25.1
[2023-04-16T13:38:19.689+0000] {process_utils.py:187} INFO - 
[2023-04-16T13:38:19.691+0000] {process_utils.py:187} INFO - [notice] A new release of pip is available: 23.0.1 -> 23.1
[2023-04-16T13:38:19.692+0000] {process_utils.py:187} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2023-04-16T13:38:21.288+0000] {process_utils.py:179} INFO - Executing cmd: /tmp/venvwz3jbw_n/bin/python /tmp/venvwz3jbw_n/script.py /tmp/venvwz3jbw_n/script.in /tmp/venvwz3jbw_n/script.out /tmp/venvwz3jbw_n/string_args.txt
[2023-04-16T13:38:21.353+0000] {process_utils.py:183} INFO - Output:
[2023-04-16T13:38:33.544+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-04-16T13:38:33.590+0000] {taskinstance.py:1332} INFO - Marking task as SUCCESS. dag_id=joke_collector, task_id=joke_collector_task, execution_date=20230415T151800, start_date=20230416T133700, end_date=20230416T133833
[2023-04-16T13:38:33.695+0000] {local_task_job.py:212} INFO - Task exited with return code 0
[2023-04-16T13:38:33.849+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
